# Deep Learning from Scratch 2 - 간단한 학습 원리

## 순방향 연산 과정

In [1]:
import random
import numpy as np

#  input data

X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

# 시그모이드 함수 정의
def sigmoid(x) :
    return 1.0 / (1.0 + np.exp(-x))

# 가중치 랜덤 선택
w = 2*np.random.random((1, 3)) - 1

# 추론 결과 확인
N = 4
for k in range(N) :
    x = X[k, :].T
    v = np.matmul(w, x)
    y = sigmoid(v)

    print(v)

[0.17207636]
[-0.25194953]
[0.67963894]
[0.25561305]


## label 데이터 설정

In [2]:
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

D = np.array([[0], [0], [1], [1]])

## 모델의 출력(순방향 연산)을 계산하는 함수 정의

In [3]:
def calc_output(W, x) :
    v = np.matmul(W, x)
    y = sigmoid(v)

    return y

## 오차 계산 함수 정의

In [4]:
def calc_error(d, y) :
    e = d - y
    delta = y * (1 - y) * e

    return delta

## 한 epoch에 수행되는 W의 업데이트 계산

In [5]:
def delta_GD(W, X, D, alpha) :
    for k in range(4) :
        x = X[k, :].T
        d = D[k]

        y = calc_output(W, x)       # 순방향연산 결과
        delta = calc_error(d, y)

        dW = alpha * delta * x  # 가중치 변화량 : alpha(learning rate) * delta * x
        W = W + dW

    return W

## 가중치 초기화 후 학습

In [6]:
W = 2 * np.random.random((1, 3)) - 1

alpha = 0.9

for epoch in range(10000) :
    W = delta_GD(W, X, D, alpha)
    print(W)

[[-0.1113082   0.03774638  0.1896059 ]]
[[0.1220154  0.03218864 0.18280514]]
[[0.33114127 0.01513375 0.15271022]]
[[ 0.51896331 -0.00924428  0.10505706]]
[[ 0.6895258  -0.03705871  0.04630778]]
[[ 0.84622166 -0.06546484 -0.01829608]]
[[ 0.99150104 -0.09265566 -0.08507025]]
[[ 1.12706685 -0.11764027 -0.15165221]]
[[ 1.25412488 -0.13999601 -0.21664598]]
[[ 1.37357289 -0.15965753 -0.27930277]]
[[ 1.48612148 -0.17676063 -0.33927955]]
[[ 1.59236472 -0.1915382  -0.39647383]]
[[ 1.69281941 -0.20425679 -0.45091814]]
[[ 1.78794637 -0.21518132 -0.50271613]]
[[ 1.87816196 -0.22455744 -0.55200513]]
[[ 1.96384485 -0.2326043  -0.59893516]]
[[ 2.04534022 -0.23951303 -0.64365737]]
[[ 2.12296295 -0.24544807 -0.68631806]]
[[ 2.19700028 -0.25054982 -0.7270557 ]]
[[ 2.26771411 -0.2549376  -0.7659998 ]]
[[ 2.33534324 -0.25871267 -0.80327055]]
[[ 2.40010542 -0.2619609  -0.83897906]]
[[ 2.4621993  -0.26475514 -0.87322782]]
[[ 2.52180618 -0.26715736 -0.90611126]]
[[ 2.57909167 -0.26922026 -0.93771634]]
[[ 2.6

## 학습 완료 후 다시 순방향 연산

In [8]:
N = 4

for k in range(N) :
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)

    print(y)

[0.01020089]
[0.0082957]
[0.99324074]
[0.99168545]


In [9]:
D

array([[0],
       [0],
       [1],
       [1]])