# 오차 역전파 (Back Propagation)

- XOR 데이터를 활용하여 오차 역전파 확인

## XOR 데이터

In [3]:
import numpy as np

X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

D = np.array([
    [0], [1], [1], [0]
])

W = 2 * np.random.random((1, 3)) -1

In [18]:
X[0].reshape(1,3).shape

(1, 3)

## 한 epoch에 수행되는 W의 업데이트 계산

In [4]:
# 시그모이드 함수 정의
def sigmoid(x) :
    return 1.0 / (1.0 + np.exp(-x))

# 모델 출력 (순방향연산) 계산
def calc_output(W, x) :
    v = np.matmul(W, x)
    y = sigmoid(v)

    return y

# 오차 계산 함수
def calc_error(d, y) :
    e = d - y
    delta = y * (1 - y) * e

    return delta


def delta_GD(W, X, D, alpha) :
    for k in range(4) :
        x = X[k, :].T
        d = D[k]

        y = calc_output(W, x)       # 순방향연산 결과
        delta = calc_error(d, y)

        dW = alpha * delta * x  # 가중치 변화량 : alpha(learning rate) * delta * x
        W = W + dW

    return W

## 가중치 초기화 후 학습

In [5]:
W = 2 * np.random.random((1, 3)) - 1

alpha = 0.9

for epoch in range(10000) :
    W = delta_GD(W, X, D, alpha)
    print(W)

[[-0.06109513  0.38745704  0.45747988]]
[[-0.09971899  0.32257617  0.35330202]]
[[-0.13238803  0.26630675  0.26905421]]
[[-0.15891485  0.21909256  0.2033441 ]]
[[-0.17972038  0.18030319  0.15355255]]
[[-0.19556969  0.14876737  0.11669652]]
[[-0.20734258  0.12317621  0.0899682 ]]
[[-0.21588498  0.10230941  0.07097453]]
[[-0.22193556  0.08512902  0.05778933]]
[[-0.22610289  0.0707973   0.04891466]]
[[-0.22886999  0.05865918  0.04321017]]
[[-0.23061091  0.04821229  0.03981955]]
[[-0.23161024  0.03907601  0.03810554]]
[[-0.23208186  0.03096403  0.03759687]]
[[-0.23218485  0.02366175  0.03794669]]
[[-0.23203658  0.01700855  0.03890065]]
[[-0.23172296  0.01088404  0.04027285]]
[[-0.23130639  0.00519771  0.04192788]]
[[-2.30831775e-01 -1.18826993e-04  4.37674301e-02]]
[[-0.23033112 -0.00511761  0.04572039]]
[[-0.2298269  -0.00983863  0.04773558]]
[[-0.22933465 -0.01431296  0.04977638]]
[[-0.2288648  -0.01856509  0.05181678]]
[[-0.2284241  -0.02261464  0.05383849]]
[[-0.22801666 -0.02647759  0

## 학습 완료 후 다시 순방향연산 결과 확인

In [6]:
N = 4

for k in range(N) :
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)

    print(y)

[0.52965337]
[0.5]
[0.47034663]
[0.44090112]


# Backpropagation 구현
## output 계산 함수

In [7]:
def calc_output(W1, W2, x) :
    v1 = np.matmul(W1, x)
    y1 = sigmoid(v1)
    v = np.matmul(W2, y1)
    y = sigmoid(v)

    return y, y1

## step 1 : 출력층의 델타 계산

In [8]:
def calc_delta(d, y) :
    e = d - y
    delta = y * (1 - y) * e

    return delta

## step 2 : 은닉층의 델타 계산

In [9]:
def calc_delta1(W2, delta, y1) :
    e1 = np.matmul(W2.T, delta)
    delta1 = y1 * (1 - y1) * e1

    return delta1

## 역전파 코드 정리

In [10]:
def backprop_XOR(W1, W2, X, D, alpha) :
    for k in range(4) :
        x = X[k, :].T
        d = D[k]

        y, y1 = calc_output(W1, W2, x)  # 순방향연산 결과
        delta = calc_delta(d, y)        # 출력층과 label 데이터 사이의 오차(델타)
        delta1 = calc_delta1(W2, delta, y1) # 은닉층의 델타

        dW1 = (alpha*delta1).reshape(4, 1) * x.reshape(1, 3)    # 가중치 업데이트 (W1)
        W1 = W1 + dW1

        dW2 = alpha * delta * y1    # 가중치 업데이트 (W2)
        W2 = W2 + dW2

    return W1, W2

## 학습 후 순방향연산 결과 확인

In [11]:
X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

D = np.array([
    [0], [1], [1], [0]
])

W1 = 2 * np.random.random((4, 3)) -1
W2 = 2 * np.random.random((1, 4)) -1

In [12]:
alpha = 0.9

for epoch in range(10000) :
    W1, W2 = backprop_XOR(W1, W2, X, D, alpha)

In [13]:
N = 4

for k in range(N) :
    x = X[k, :].T
    v1 = np.matmul(W1, x)
    y1 = sigmoid(v1)
    v = np.matmul(W2, y1)
    y = sigmoid(v)

    print(y)

[0.00875757]
[0.98948971]
[0.98951676]
[0.01195728]


In [14]:
def MSE(target, y) :
    result = 0
    for i, n in enumerate(target) :
        result += 0.5 * (target[i] - y[i]) ** 2
    
    return result

MSE([0.2, 0.7], [0.57, 0.61])   # 0.072

0.07249999999999998